

1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:

a) Addition of 2 in all the element

b) Multiply 3 with all the elements

c) Divide every element by 2



In [1]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5])
print(arr +2)
print(arr*3)
print(arr/2)

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


Q.2 Questions on Basic NumPy Array:

a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

b) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [6]:
print(arr[::-1])

[5 4 3 2 1]


In [8]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
mostx = np.bincount(x).argmax();
indices = np.where(x==mostx)[0]
print(mostx)
print(indices,end='\n\n')

mosty = np.bincount(y).argmax();
iy = np.where(y==mostx)[0]
print(mosty)
print(iy)


1
[0 5 7 8 9]

1
[0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:

a) Access 1st row, 2nd column

b) Access 3rd row, 1st column

In [9]:
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a[0,1])
print(a[2,0])

20
70


Q.4 Write program to create an 1-D NumPy array named Your Name with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [26]:
Ashish = np.linspace(10,100,25)
print(Ashish.ndim)
print(Ashish.shape)
print(Ashish.size)
print(Ashish.dtype)
print(Ashish.nbytes)
print(Ashish.reshape(25,1))
print(Ashish)
print(Ashish.T)
print(Ashish)
#No change in orginal shape if we use .T for transpose

1
(25,)
25
float64
200
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Create a 2-D Array of three rows and four columns, named ucs420_your_name
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_your_name. Resize the array to two rows and three
columns and name it as resized_ ucs420_your_name.

In [27]:
ucs420 = np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print("Mean",np.mean(ucs420))
print("Median",np.median(ucs420))
print("Max",np.max(ucs420))
print("Min",np.min(ucs420))
print("Uniques",np.unique(ucs420))


print("reshaping")
print(ucs420.reshape(4,3))

print("resizing")
print(np.resize(ucs420,(2,3)))


Mean 43.333333333333336
Median 37.5
Max 90
Min 10
Uniques [10 15 20 30 35 40 50 60 70 80 90]
reshaping
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
resizing
[[10 20 30]
 [40 50 60]]
